# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NPCRI
                                 A QGIS plugin
 Normalized Pigment Chlorophyll Ratio Index
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-17
        copyright            : (C) 2020 by mathi
        email                : arivumathis@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NPCRI class from file NPCRI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .NPCRI import NPCRI
    return NPCRI(iface)
